
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=sensor
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xyz123
    volumes:
      - .influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  api:
    build: .
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=xyz123
      - INFLUX_ORG=sensor
      - INFLUX_BUCKET=sensor-bucket
      - TOKEN=abc123
    depends_on:
      - influxdb
